title: Radiology Masters
description: Radiology video tutorials to speed up your boards and FRCR exam learning. Take the tutor with you with our expert radiologist guides.
logo: /assets/img/logo-48.png
author: https://radiologymasters.com
twitter:
  username: rad_masters
  card: summary

mode: free

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
script_path: /assets/js

# Build settings
markdown: kramdown
permalink: pretty

#plugins:
  - jekyll-seo-tag

collections:
  cases:
    output: true
    permalink: /cases/:title/
  authors:
    output: true
    permalink: /authors/:title/
  pages:
    permalink: /:title/
  posts:
    permalink: /:year/:title/

defaults:
  -
    scope:
      type: "cases"
    values:
      layout: "case"

# Speciality list - used to populate the header navigation amongst other things
specialities:
  - slug: gastrointestinal
    name: Gastrointestinal
    order: 1
  - slug: musculoskeletal
    name: Musculoskeletal
    order: 0
  - slug: chest
    name: Chest
    order: 2
  - slug: neuro
    name: Neuro
    order: 3
  - slug: headneck
    name: Head & Neck
    order: 4
  - slug: breast
    name: Breast
    order: 5
  - slug: genitourinary
    name: Genitourinary
    order: 6
  - slug: paediatric
    name: Paediatric
    order: 8
  - slug: frcr-exam-tips
    name: FRCR Exam
    order: 9


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
